(() => {
  "use strict";
  const MP_VERSION="1.0.1", MP_BUNDLE=`https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@${MP_VERSION}/vision_bundle.mjs`, MP_WASM=`https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@${MP_VERSION}/wasm`, FACE_MODEL="https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task";
  const PREVIEW_MAX=720,PHOTO_MAX=1600,FPS=8; const video=document.getElementById("video"),canvas=document.getElementById("previewCanvas"),placeholder=document.getElementById("placeholder"),status=document.getElementById("status"),startBtn=document.getElementById("startCamera"),switchBtn=document.getElementById("switchCamera"),captureBtn=document.getElementById("capture"),saveBtn=document.getElementById("download"),resetBtn=document.getElementById("reset");
  const sliders={smooth:document.getElementById("smooth"),soften:document.getElementById("soften"),whiten:document.getElementById("whiten"),makeup:document.getElementById("makeup")},values={smooth:document.getElementById("smoothValue"),soften:document.getElementById("softenValue"),whiten:document.getElementById("whitenValue"),makeup:document.getElementById("makeupValue")};
  const detectCanvas=document.createElement("canvas"),detectCtx=detectCanvas.getContext("2d"); let stream=null,sourceKind=null,facing="user",mirrored=true,raf=0,lastFrame=0,faceLandmarker=null,faceInit=null,stableFaces=[];
  const setStatus=t=>{if(status)status.textContent=t},updateLabels=()=>Object.keys(sliders).forEach(k=>{if(values[k])values[k].textContent=sliders[k].value});
  const params=()=>({smooth:+sliders.smooth.value/100,soften:+sliders.soften.value/100,whiten:+sliders.whiten.value/100,makeup:+sliders.makeup.value/100});
  function setMirror(v){mirrored=!!v;video.style.transform=mirrored?"scaleX(-1)":"none";canvas.style.transform=mirrored?"scaleX(-1)":"none"}
  function stopCamera(){if(raf)cancelAnimationFrame(raf);raf=0;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null}
  async function initFace(){if(faceLandmarker)return faceLandmarker;if(faceInit)return faceInit;faceInit=(async()=>{try{setStatus("相機已開啟 · 載入臉部追蹤…");const v=await import(MP_BUNDLE),r=await v.FilesetResolver.forVisionTasks(MP_WASM);faceLandmarker=await v.FaceLandmarker.createFromOptions(r,{baseOptions:{modelAssetPath:FACE_MODEL,delegate:"CPU"},runningMode:"IMAGE",numFaces:1,minFaceDetectionConfidence:.30,minFacePresenceConfidence:.30,minTrackingConfidence:.30});return faceLandmarker}catch(e){setStatus(`臉部追蹤載入失敗 · ${e?.message||e?.name||e}`);return null}finally{faceInit=null}})();return faceInit}
  function stabilize(next){if(!next.length){stableFaces=[];return}if(!stableFaces.length){stableFaces=next;return}const a=stableFaces[0],b=next[0],o=[];for(let i=0;i<b.length;i++){const p=b[i],q=a[i]||p;o.push({x:q.x*.72+p.x*.28,y:q.y*.72+p.y*.28,z:q.z*.72+p.z*.28})}stableFaces=[o]}
  function detectFace(){if(!faceLandmarker||video.readyState<2||!video.videoWidth)return;const s=Math.min(1,PREVIEW_MAX/Math.max(video.videoWidth,video.videoHeight));detectCanvas.width=Math.round(video.videoWidth*s);detectCanvas.height=Math.round(video.videoHeight*s);detectCtx.drawImage(video,0,0,detectCanvas.width,detectCanvas.height);try{stabilize(faceLandmarker.detect(detectCanvas)?.faceLandmarks||[])}catch(e){stableFaces=[]}const p=params();setStatus(`美肌 ${sliders.smooth.value}% · 磨皮 ${sliders.soften.value}% · 美白 ${sliders.whiten.value}% · 彩妝 ${sliders.makeup.value}% · 偵測 ${stableFaces.length} 張臉`)}
  const OVAL=[10,338,297,332,284,251,389,356,454,323,361,288,397,365,379,378,400,377,152,148,176,149,150,136,172,58,132,93,234,127,162,21,54,103,67,109],EYES=[[33,7,163,144,145,153,154,155,133,173,157,158,159,160,161,246],[362,382,381,380,374,373,390,249,263,466,388,387,386,385,384,398]],MOUTH=[61,146,91,181,84,17,314,405,321,375,291,308,324,318,402,317,14,87,178,88,95,78],NOSE=[1,2,98,327,168,197,5,4,51,281];
  function mask(f,W,H){const c=document.createElement("canvas");c.width=W;c.height=H;const x=c.getContext("2d");const p=OVAL.map(i=>f[i]).filter(Boolean).map(q=>[q.x*W,q.y*H]);x.fillStyle="#fff";x.beginPath();x.moveTo(...p[0]);p.slice(1).forEach(q=>x.lineTo(...q));x.closePath();x.fill();x.globalCompositeOperation="destination-out";for(const ids of [...EYES,MOUTH,NOSE]){const q=ids.map(i=>f[i]).filter(Boolean).map(z=>[z.x*W,z.y*H]);x.beginPath();x.moveTo(...q[0]);q.slice(1).forEach(z=>x.lineTo(...z));x.closePath();x.fill()}const d=x.getImageData(0,0,W,H).data,m=new Uint8Array(W*H);for(let i=0;i<m.length;i++)m[i]=d[i*4];return m}
  function blur(src,W,H,r){const c=document.createElement("canvas");c.width=W;c.height=H;const x=c.getContext("2d");x.filter=`blur(${r}px)`;x.drawImage(src,0,0,W,H);return x.getImageData(0,0,W,H).data}
  function beauty(src,w,h,max){const sc=Math.min(1,max/Math.max(w,h)),W=Math.round(w*sc),H=Math.round(h*sc);canvas.width=W;canvas.height=H;const x=canvas.getContext("2d",{willReadFrequently:true});x.drawImage(src,0,0,W,H);const base=x.getImageData(0,0,W,H),out=new Uint8ClampedArray(base.data),p=params();if(!stableFaces.length)return new ImageData(out,W,H);const m=mask(stableFaces[0],W,H),b=blur(src,W,H,1.5+3.5*p.smooth+2*p.soften);for(let k=0,i=0;i<out.length;i+=4,k++){const a=m[k]/255;if(a<.05)continue;let r=base.data[i],g=base.data[i+1],bb=base.data[i+2],mix=Math.min(.72,(.12+.55*p.smooth+.32*p.soften)*a);r+=(b[i]-r)*mix;g+=(b[i+1]-g)*mix;bb+=(b[i+2]-bb)*mix;if(p.whiten){const v=24*p.whiten*a;r=Math.min(255,r+v*.96);g=Math.min(255,g+v);bb=Math.min(255,bb+v*.98)}out[i]=r;out[i+1]=g;out[i+2]=bb}return new ImageData(out,W,H)}
  function render(src,max){const d=beauty(src,src.videoWidth||src.width,src.videoHeight||src.height,max),x=canvas.getContext("2d");x.putImageData(d,0,0);window.BeautyCamMakeup?.render?.(x,stableFaces,d.width,d.height,{amount:params().makeup});}
  async function start(){stopCamera();try{stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:960}}});video.srcObject=stream;await video.play();sourceKind="camera";captureBtn.disabled=false;switchBtn.disabled=false;startBtn.textContent=facing==="user"?"前鏡頭已開啟":"後鏡頭已開啟";setMirror(facing==="user");video.style.display="block";canvas.style.display="none";placeholder.style.display="none";if(!(await initFace()))return;video.style.display="none";canvas.style.display="block";loop()}catch(e){stopCamera();setStatus("無法開啟相機");captureBtn.disabled=true;switchBtn.disabled=true}}
  function loop(){const iv=1000/FPS;const tick=t=>{raf=requestAnimationFrame(tick);if(sourceKind!=="camera"||video.readyState<2||t-lastFrame<iv)return;lastFrame=t;detectFace();render(video,PREVIEW_MAX);setMirror(facing==="user")};raf=requestAnimationFrame(tick)}
  function flip(){const t=document.createElement("canvas");t.width=canvas.width;t.height=canvas.height;const c=t.getContext("2d");c.translate(t.width,0);c.scale(-1,1);c.drawImage(canvas,0,0);const x=canvas.getContext("2d");x.setTransform(1,0,0,1,0,0);x.clearRect(0,0,canvas.width,canvas.height);x.drawImage(t,0,0)}
  async function capture(){if(sourceKind!=="camera")return;if(raf)cancelAnimationFrame(raf);detectFace();render(video,PHOTO_MAX);if(facing==="user")flip();canvas.style.transform="none";saveBtn.disabled=false;stopCamera();sourceKind="photo-capture";switchBtn.disabled=true;startBtn.textContent="開啟前鏡頭"}
  function reset(){stopCamera();stableFaces=[];sourceKind=null;canvas.style.display="none";video.style.display="none";placeholder.style.display="grid";captureBtn.disabled=true;switchBtn.disabled=true;saveBtn.disabled=true;facing="user";setMirror(true);startBtn.textContent="開啟前鏡頭";setStatus("已重設")}
  startBtn.addEventListener("click",start);switchBtn.addEventListener("click",()=>{facing=facing==="user"?"environment":"user";start()});captureBtn.addEventListener("click",capture);resetBtn.addEventListener("click",reset);Object.values(sliders).forEach(s=>s?.addEventListener("input",updateLabels));window.addEventListener("pagehide",stopCamera);window.addEventListener("beforeunload",stopCamera);updateLabels();setMirror(true);window.BeautyCamEngine={getFaces:()=>stableFaces,getMirror:()=>mirrored,getCanvas:()=>canvas};
})();