(() => {
  "use strict";
  const MAX_PHOTO_SIZE=1600, CAMERA_PROCESS_SIZE=960, PREVIEW_FPS=10;
  const FACE_MODEL_URL="https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task";
  const WASM_URL="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/wasm";
  const video=document.getElementById("video"), canvas=document.getElementById("previewCanvas"), placeholder=document.getElementById("placeholder");
  const startBtn=document.getElementById("startCamera"), switchBtn=document.getElementById("switchCamera"), captureBtn=document.getElementById("capture"), saveBtn=document.getElementById("download"), resetBtn=document.getElementById("reset"), status=document.getElementById("status");
  const sliders={smooth:document.getElementById("smooth"),soften:document.getElementById("soften"),whiten:document.getElementById("whiten"),makeup:document.getElementById("makeup")};
  const values={smooth:document.getElementById("smoothValue"),soften:document.getElementById("softenValue"),whiten:document.getElementById("whitenValue"),makeup:document.getElementById("makeupValue")};
  let stream=null, sourceKind=null, raf=0, lastFrame=0, faceLandmarker=null, faceInit=null, latestFaces=[], lastFace=-Infinity, facing="user", mirrored=true;
  const OVAL=[10,338,297,332,284,251,389,356,454,323,361,288,397,365,379,378,400,377,152,148,176,149,150,136,172,58,132,93,234,127,162,21,54,103,67,109];
  const EYES=[[33,7,163,144,145,153,154,155,133,173,157,158,159,160,161,246],[362,382,381,380,374,373,390,249,263,466,388,387,386,385,384,398]];
  const MOUTH=[61,146,91,181,84,17,314,405,321,375,291,308,324,318,402,317,14,87,178,88,95,78];
  const NOSE=[1,2,98,327,168,197,5,4,51,281];
  const setStatus=t=>{if(status)status.textContent=t};
  const fit=(w,h,max)=>{const s=Math.min(1,max/Math.max(w,h));return{width:Math.max(1,Math.round(w*s)),height:Math.max(1,Math.round(h*s))}};
  function params(){return{smooth:+sliders.smooth.value/100,soften:+sliders.soften.value/100,whiten:+sliders.whiten.value/100,makeup:+sliders.makeup.value/100}}
  function labels(){for(const k in sliders)if(values[k])values[k].textContent=sliders[k].value}
  function mirrorDisplay(v){mirrored=!!v;canvas.style.transform=mirrored?"scaleX(-1)":"none"}
  function release(){if(raf)cancelAnimationFrame(raf);raf=0;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null}
  async function initFace(){if(faceLandmarker)return faceLandmarker;if(faceInit)return faceInit;faceInit=(async()=>{try{setStatus("相機已開啟，正在載入臉部追蹤引擎…");const vision=await import("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.js");const resolver=await vision.FilesetResolver.forVisionTasks(WASM_URL);faceLandmarker=await vision.FaceLandmarker.createFromOptions(resolver,{baseOptions:{modelAssetPath:FACE_MODEL_URL,delegate:"GPU"},runningMode:"VIDEO",numFaces:5,minFaceDetectionConfidence:.5,minFacePresenceConfidence:.5,minTrackingConfidence:.5,outputFaceBlendshapes:false});setStatus("臉部追蹤已就緒 · 等待偵測…");return faceLandmarker}catch(e){console.error("Face Landmarker init",e);setStatus(`臉部追蹤載入失敗 · ${e?.name||"錯誤"}`);return null}finally{faceInit=null}})();return faceInit}
  function detect(source,t){if(!faceLandmarker||!source)return;try{const r=faceLandmarker.detectForVideo(source,t);latestFaces=r?.faceLandmarks||[];lastFace=t}catch(e){console.warn("face detect",e);setStatus(`臉部追蹤錯誤 · ${e?.name||"錯誤"}`)}}
  function polygon(ctx,face,ids,w,h){const p=ids.map(i=>face[i]).filter(Boolean).map(q=>[q.x*w,q.y*h]);if(p.length<3)return p;ctx.beginPath();ctx.moveTo(...p[0]);for(let i=1;i<p.length;i++)ctx.lineTo(...p[i]);ctx.closePath();return p}
  function inside(x,y,p){let ok=false;for(let i=0,j=p.length-1;i<p.length;j=i++)if(((p[i][1]>y)!=(p[j][1]>y))&&x<(p[j][0]-p[i][0])*(y-p[i][1])/((p[j][1]-p[i][1])||1e-9)+p[i][0])ok=!ok;return ok}
  function faceMask(w,h,faces){const c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d");x.fillStyle="#fff";for(const f of faces){const p=polygon(x,f,OVAL,w,h);if(p.length)x.fill();}for(const f of faces)for(const ids of [...EYES,MOUTH,NOSE]){const p=ids.map(i=>f[i]).filter(Boolean).map(q=>[q.x*w,q.y*h]);if(p.length<3)continue;const xs=p.map(q=>q[0]),ys=p.map(q=>q[1]);for(let y=Math.max(0,Math.floor(Math.min(...ys)-2));y<=Math.min(h-1,Math.ceil(Math.max(...ys)+2));y++)for(let xx=Math.max(0,Math.floor(Math.min(...xs)-2));xx<=Math.min(w-1,Math.ceil(Math.max(...xs)+2));xx++)if(inside(xx+.5,y+.5,p))x.clearRect(xx,y,1,1)}const d=x.getImageData(0,0,w,h).data,m=new Uint8Array(w*h);for(let i=0;i<m.length;i++)m[i]=d[i*4];return m}
  function blur(source,w,h,r){const c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d",{willReadFrequently:true});x.filter=`blur(${r}px)`;x.drawImage(source,0,0,w,h);x.filter="none";return x.getImageData(0,0,w,h).data}
  function feather(mask,w,h,r){const c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d",{willReadFrequently:true}),d=new Uint8ClampedArray(w*h*4);for(let i=0;i<mask.length;i++)d[i*4]=d[i*4+1]=d[i*4+2]=mask[i],d[i*4+3]=255;x.putImageData(new ImageData(d,w,h),0,0);x.filter=`blur(${r}px)`;x.drawImage(c,0,0);return x.getImageData(0,0,w,h).data}
  function skin(r,g,b,y,ch){if(y<24||y>250||ch<3)return 0;const warm=r>=g*.82&&g>=b*.70,rose=r>g&&g>=b*.88,yellow=g>=b*1.06,neutral=ch<26&&r>=g*.93&&g>=b*.89;if(!warm||(!rose&&!yellow&&!neutral))return 0;const v=Math.min(1,Math.max(0,(r-g)/75)*.43+Math.max(0,g-b)/90*.37+Math.min(1,ch/50)*.2);return Math.max(.08,Math.min(1,v*(1-Math.min(1,Math.abs(y-150)/130)*.28)+(neutral?.16:0)))}
  function process(source,w,h,max,capture){const s=fit(w,h,max);canvas.width=s.width;canvas.height=s.height;const ctx=canvas.getContext("2d",{willReadFrequently:true});ctx.drawImage(source,0,0,s.width,s.height);const base=ctx.getImageData(0,0,s.width,s.height),out=new Uint8ClampedArray(base.data),p=params(),faces=latestFaces;const active=p.smooth||p.soften||p.whiten;const mask=faceMask(s.width,s.height,faces),has=faces.length>0;if(!active)return new ImageData(out,s.width,s.height);const f=feather(mask,s.width,s.height,Math.max(3,Math.round(s.width/250))),b=blur(source,s.width,s.height,1.8+4.2*p.smooth+2.8*p.soften),detail=blur(source,s.width,s.height,.8),glow=blur(source,s.width,s.height,9+8*p.soften);const strength=Math.min(.48,p.smooth*.38+p.soften*.42)*(faces.length>2?.84:faces.length===2?.94:1),boost=capture?1.08:1;for(let i=0,k=0;i<out.length;i+=4,k++){const r=base.data[i],g=base.data[i+1],bb=base.data[i+2],y=.2126*r+.7152*g+.0722*bb,ch=Math.max(r,g,bb)-Math.min(r,g,bb),gate=Math.min(1,skin(r,g,bb,y,ch)*(has?f[k*4]/255:1));if(gate>.035&&strength){const d=Math.min(1,(Math.abs(r-b[i])+Math.abs(g-b[i+1])+Math.abs(bb-b[i+2]))/105),mix=Math.min(.5,strength*gate*Math.max(.28,1-.58*d)*boost);out[i]=r+(b[i]-r)*mix;out[i+1]=g+(b[i+1]-g)*mix;out[i+2]=bb+(b[i+2]-bb)*mix}if(gate>.035){let rr=out[i],gg=out[i+1],bl=out[i+2],yy=.2126*rr+.7152*gg+.0722*bl;const red=Math.max(0,rr-gg),rc=Math.min(4.5,red*.055)*gate*(.55+p.soften*.45);rr-=rc;gg+=rc*.16;const shadow=Math.max(0,158-yy)/158,lift=shadow*(4.2+4*p.soften)*gate;rr+=lift*.96;gg+=lift;bl+=lift*.98;if(p.whiten){const head=Math.max(0,250-yy)/205,v=p.whiten*(20+10*p.soften)*head*gate;rr+=v*.965;gg+=v;bl+=v*.985}if(p.soften){const gy=.2126*glow[i]+.7152*glow[i+1]+.0722*glow[i+2],q=Math.max(0,Math.min(1,(gy-92)/145)),v=p.soften*5.2*q*gate;rr+=v*.97;gg+=v;bl+=v*.99}const av=(rr+gg+bl)/3,sat=1+p.smooth*.035;rr=av+(rr-av)*sat;gg=av+(gg-av)*sat;bl=av+(bl-av)*sat;out[i]=Math.max(0,Math.min(255,rr));out[i+1]=Math.max(0,Math.min(255,gg));out[i+2]=Math.max(0,Math.min(255,bl))}void detail}return new ImageData(out,s.width,s.height)}
  function render(source,max,capture=false){const data=process(source,source.videoWidth||source.width,source.videoHeight||source.height,max,capture);const x=canvas.getContext("2d");x.putImageData(data,0,0);if(window.BeautyCamMakeup)window.BeautyCamMakeup.render(x,latestFaces,data.width,data.height,{amount:+sliders.makeup.value/100});const mv=+sliders.makeup.value;setStatus(faceLandmarker?`彩妝 ${mv}% · 偵測 ${latestFaces.length} 張臉 · V1.6.4`:"正在載入臉部追蹤…")}
  async function openStream(){try{return await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:960}}})}catch(e){return navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:facing}})}}
  async function start(){release();if(!navigator.mediaDevices?.getUserMedia){setStatus("目前環境不支援相機，請使用 HTTPS 網頁");return}try{stream=await openStream();video.srcObject=stream;await video.play();sourceKind="camera";latestFaces=[];lastFace=-Infinity;captureBtn.disabled=false;switchBtn.disabled=false;startBtn.textContent=facing==="user"?"前鏡頭已開啟":"後鏡頭已開啟";mirrorDisplay(facing==="user");canvas.style.display="block";video.style.display="none";placeholder.style.display="none";setStatus("正在啟動臉部追蹤…");await initFace();loop()}catch(e){release();setStatus(e?.name==="NotAllowedError"?"相機權限被拒絕，請允許此網站使用相機":e?.name==="NotFoundError"?"找不到可用的相機":e?.name==="NotReadableError"?"相機目前被其他程式占用":"無法開啟相機，請確認 Safari 的相機權限");captureBtn.disabled=true;switchBtn.disabled=true}}
  function loop(){const interval=1000/PREVIEW_FPS;const tick=t=>{raf=requestAnimationFrame(tick);if(sourceKind!=="camera"||video.readyState<2||t-lastFrame<interval)return;lastFrame=t;detect(video,t);render(video,CAMERA_PROCESS_SIZE,false)};raf=requestAnimationFrame(tick)}
  function flip(){const t=document.createElement("canvas");t.width=canvas.width;t.height=canvas.height;const x=t.getContext("2d");x.translate(t.width,0);x.scale(-1,1);x.drawImage(canvas,0,0);const c=canvas.getContext("2d");c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,canvas.width,canvas.height);c.drawImage(t,0,0)}
  async function capture(){if(sourceKind!=="camera"||!video.videoWidth)return;if(raf)cancelAnimationFrame(raf);raf=0;detect(video,performance.now());render(video,MAX_PHOTO_SIZE,true);if(facing==="user")flip();canvas.style.transform="none";saveBtn.disabled=false;setStatus(`拍照完成：${latestFaces.length?`偵測 ${latestFaces.length} 張臉，`:""}V1.6.4 美顏與彩妝已合成`);release();sourceKind="photo-capture";switchBtn.disabled=true;startBtn.textContent="開啟前鏡頭"}
  function reset(){release();latestFaces=[];sourceKind=null;canvas.style.display="none";canvas.style.transform="none";video.style.display="none";placeholder.style.display="grid";captureBtn.disabled=true;switchBtn.disabled=true;saveBtn.disabled=true;facing="user";mirrorDisplay(true);startBtn.textContent="開啟前鏡頭";setStatus("已重設")}
  switchBtn.addEventListener("click",()=>{facing=facing==="user"?"environment":"user";start()});startBtn.addEventListener("click",start);captureBtn.addEventListener("click",capture);resetBtn.addEventListener("click",reset);Object.values(sliders).forEach(s=>s?.addEventListener("input",labels));window.addEventListener("pagehide",release);window.addEventListener("beforeunload",release);labels();mirrorDisplay(true);
  window.BeautyCamEngine={getFaces:()=>latestFaces,getMirror:()=>mirrored,getCanvas:()=>canvas};
})();