(() => {
  "use strict";
  const BL=[70,63,105,66,107],BR=[336,296,334,293,300];
  const P={natural:{blush:[228,82,104],shadow:[151,91,132],lip:[202,68,88],brow:[68,45,42]},rose:{blush:[242,72,104],shadow:[169,70,145],lip:[216,48,82],brow:[62,40,42]},warm:{blush:[238,111,72],shadow:[170,91,62],lip:[207,61,52],brow:[72,48,38]}};
  let style="natural",amount=0,browShape="natural",lipShape="natural";
  const pt=(f,i,w,h)=>f?.[i]?[f[i].x*w,f[i].y*h]:null,dist=(a,b)=>a&&b?Math.hypot(a[0]-b[0],a[1]-b[1]):0,rgba=(c,a)=>`rgba(${c[0]},${c[1]},${c[2]},${Math.max(0,Math.min(1,a))})`;
  function glow(x,cx,cy,rx,ry,c,a){x.save();const g=x.createRadialGradient(cx,cy,0,cx,cy,Math.max(rx,ry));g.addColorStop(0,rgba(c,a));g.addColorStop(.55,rgba(c,a*.48));g.addColorStop(1,rgba(c,0));x.fillStyle=g;x.beginPath();x.ellipse(cx,cy,rx,ry,0,0,Math.PI*2);x.fill();x.restore()}
  function line(x,p,c,w,a){p=p.filter(Boolean);if(p.length<2)return;x.save();x.strokeStyle=rgba(c,a);x.lineWidth=w;x.lineCap="round";x.lineJoin="round";x.beginPath();x.moveTo(...p[0]);for(let i=1;i<p.length;i++)x.lineTo(...p[i]);x.stroke();x.restore()}
  function blush(x,f,w,h,c,a,side){const outer=pt(f,side?454:234,w,h),eye=pt(f,side?263:33,w,h),chin=pt(f,152,w,h);if(!outer||!eye||!chin)return;const cx=eye[0]+(outer[0]-eye[0])*.52,cy=eye[1]+(chin[1]-eye[1])*.38;glow(x,cx,cy,dist(eye,outer)*.40,dist(eye,outer)*.20,c,.48*a)}
  function lips(x,f,w,h,c,a){const l=pt(f,61,w,h),r=pt(f,291,w,h),top=pt(f,13,w,h),bot=pt(f,14,w,h);if(!l||!r||!top||!bot)return;const wd=dist(l,r),cx=(l[0]+r[0])/2,cy=(top[1]+bot[1])/2,hh=Math.max(5,Math.abs(bot[1]-top[1])*1.35);x.save();x.fillStyle=rgba(c,.58*a);x.beginPath();x.ellipse(cx,cy,wd*.46,hh*.50,0,0,Math.PI*2);x.fill();x.globalCompositeOperation="screen";x.fillStyle=`rgba(255,210,218,${.12+.12*a})`;x.beginPath();x.ellipse(cx-wd*.10,cy-hh*.18,wd*.20,hh*.16,0,0,Math.PI*2);x.fill();x.restore()}
  function brow(x,f,w,h,c,a,ids){const p=ids.map(i=>pt(f,i,w,h)).filter(Boolean);if(p.length<3)return;const s=p[0],e=p[p.length-1],mid=p[Math.floor(p.length/2)];let m=[mid[0],mid[1]-(browShape==="arch"?w*.018:0)];if(browShape==="straight")m=[(s[0]+e[0])/2,(s[1]+e[1])/2];line(x,[s,m,e],c,Math.max(2,w*.007),.55+.25*a)}
  function eyes(x,f,w,h,c,a){const l=pt(f,33,w,h),r=pt(f,362,w,h),le=pt(f,133,w,h),re=pt(f,263,w,h);if(!l||!r||!le||!re)return;const d=dist(l,le);glow(x,(l[0]+le[0])/2,l[1]-d*.08,d*.32,d*.16,c,.28*a);glow(x,(r[0]+re[0])/2,r[1]-d*.08,d*.32,d*.16,c,.28*a)}
  function render(ctx,faces,w,h,o={}){const a=Math.max(0,Math.min(1,Number(o.amount??amount)));if(!ctx||!faces?.length||a<=.001)return;const p=P[o.style||style]||P.natural,layer=document.createElement("canvas");layer.width=w;layer.height=h;const x=layer.getContext("2d");for(const f of faces){const ed=dist(pt(f,33,w,h),pt(f,263,w,h));if(!ed)continue;eyes(x,f,w,h,p.shadow,a);blush(x,f,w,h,p.blush,a,false);blush(x,f,w,h,p.blush,a,true);lips(x,f,w,h,p.lip,a);brow(x,f,w,h,p.brow,a,BL);brow(x,f,w,h,p.brow,a,BR)}ctx.drawImage(layer,0,0)}
  window.BeautyCamMakeup={setStyle:v=>{if(P[v])style=v},setAmount:v=>{amount=Math.max(0,Math.min(1,Number(v)/100))},setBrowShape:v=>{browShape=v||"natural"},setLipShape:v=>{lipShape=v||"natural"},render};
})();