import {FaceVision} from "./vision.js";
import {stabilize,blend} from "./face.js";
import {masks,beauty,makeup} from "./effects.js";
const video=document.querySelector("#camera"),canvas=document.querySelector("#output"),ctx=canvas.getContext("2d",{willReadFrequently:true}),status=document.querySelector("#status"),hint=document.querySelector("#hint");
const vision=new FaceVision();let stream=null,facing="user",running=false,frame=0,lastTime=0,points=[],expression=[],matrix=null,look="none",captured=false;
const $=id=>document.getElementById(id),settings=()=>({soft:+$("soft").value,tone:+$("tone").value,light:+$("light").value});
function setStatus(t){status.textContent=t}
function size(max){const s=Math.min(1,max/Math.max(video.videoWidth,video.videoHeight));return[Math.max(1,Math.round(video.videoWidth*s)),Math.max(1,Math.round(video.videoHeight*s))]}
async function start(){try{stop();stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:960},frameRate:{ideal:30,max:30}}});video.srcObject=stream;await video.play();await vision.init();running=true;captured=false;$("start").disabled=true;$("switch").disabled=false;$("capture").disabled=false;$("save").disabled=true;hint.style.display="none";video.style.display="block";canvas.style.display="block";setStatus("V2.0 · Face Landmarker 已啟動");requestAnimationFrame(loop)}catch(e){setStatus("啟動失敗："+(e?.message||e))}}
function stop(){running=false;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}video.srcObject=null}
function drawFrame(max=720,detect=true){const [w,h]=size(max);canvas.width=w;canvas.height=h;ctx.save();if(facing==="user"){ctx.translate(w,0);ctx.scale(-1,1)}ctx.drawImage(video,0,0,w,h);ctx.restore();if(detect){const r=vision.detect(video);points=stabilize(points,r?.landmarks,.32);expression=r?.blendshapes||[];matrix=r?.matrix||null}if(!points.length){setStatus("V2.0 · 等待臉部");return}const renderPoints=facing==="user"?points.map(p=>({...p,x:1-p.x})):points;const data=ctx.getImageData(0,0,w,h);const m=masks(w,h,renderPoints);const out=beauty(data.data,w,h,m.face,m.protect,settings());ctx.putImageData(new ImageData(out,w,h),0,0);makeup(ctx,renderPoints,w,h,+$("makeup").value,look,expression)}
function loop(t){if(!running)return;if(t-lastTime>55){lastTime=t;drawFrame(720,true);frame++}requestAnimationFrame(loop)}
async function capture(){if(!running)return;drawFrame(1600,true);running=false;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}video.srcObject=null;captured=true;$("capture").disabled=true;$("save").disabled=false;$("start").disabled=false;setStatus("V2.0 · 高解析度影像完成")}
async function save(){if(!captured)return;const blob=await new Promise(r=>canvas.toBlob(r,"image/jpeg",.95));if(!blob)return;const file=new File([blob],`BeautyCam-V2-${Date.now()}.jpg`,{type:"image/jpeg"});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file]});return}catch(e){if(e.name==="AbortError")return}}const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function switchCam(){facing=facing==="user"?"environment":"user";points=[];expression=[];vision.reset();start()}
function reset(){stop();points=[];expression=[];matrix=null;captured=false;canvas.style.display="none";video.style.display="none";hint.style.display="grid";$("start").disabled=false;$("switch").disabled=true;$("capture").disabled=true;$("save").disabled=true;setStatus("尚未啟動")}
$("start").onclick=start;$("switch").onclick=switchCam;$("capture").onclick=capture;$("save").onclick=save;$("reset").onclick=reset;
for(const id of ["soft","tone","light","makeup"]){$(id).oninput=()=>$(id+"Value").textContent=$(id).value}
document.querySelectorAll("[data-look]").forEach(b=>b.onclick=()=>{look=b.dataset.look;document.querySelectorAll("[data-look]").forEach(x=>x.classList.toggle("active",x===b));if(look==="none")$("makeup").value=0;else if(+$("makeup").value<35)$("makeup").value=35;$("makeupValue").textContent=$("makeup").value});
